version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.security.oauth:spring-security-oauth2
    versions:
    - 2.3.5.RELEASE
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.9.8
